### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by sefabey**
'add org and speaker profiles, the former tbc

### CODE REVIEW

**Comment by DaveParr** [comment]
Current changes look good, but we need to actually add the photos and bios. 

To start with could you copy and paste my photo from my avatar on GH and see how that renders?

Socials are:
https://twitter.com/DaveParr
https://github.com/DaveParr
https://daveparr.info/

**Comment by sefabey** [comment]
Dave, I've made some changed and the build failed. Tried to debug and came to the conclusion that commenting out Speaker02.toml resulted in the fail. Uncommenting Speaker02.toml passes the build but now defaults are shown for Speaker02. Any idea how we can disable Speaker02.toml?

**Comment by sefabey** [comment]
Further to this, I guess the issue is with the team.html. 

under .Site.Params.team.speakers, editing the 'name' param from 
`              <h3>{{ .name | markdownify }}</h3>`
to 

`{{ with .name }}
              <h3>{{ . | markdownify }}</h3>
              {{ end }}  ` might actually fix this?

I did this on my local and it does seem to not break anything but I cannot push the team.html. My `git status` reads: '	modified:   themes/hugo-satrdays-theme (modified content, untracked content)' . Any idea how can I tack these subfolders (or whatever they are called).

**Comment by sefabey** [comment]
I've sent a PR to https://github.com/satRdays/hugo-satrdays-theme to reflect the changes. I really have little idea what I'm doing :D

**Review by DaveParr — COMMENTED** [review]
The commenting out of `speakers02.toml` is the problem, this file should be deleted, not commented out. Its whole intent is just to show boiler plate in a particular way, and to notify people that more files in this directory make more speaker sections. If we want less speaker sections the correct thing to do is to _delete_ this file, not uncomment it.

**Comment by DaveParr** [comment]
@sefabey thanks for doing all this work, most of it is great, but the way you've treated the speakers by uncommenting and then changing the underlying theme means I am physically unable to merge this request, as the theme changes need to be resolved first. 

I've spent a bit of time today trying to work out what happened in your repo while I was away, and I believe the following things are the least risky way to fix it.

* delete the file in speakers that you don't want
* checkout the current, correct version of the satrdays theme without the change.

Hope this makes sense, let me know if I can help out with those changes.

**Pull request closed without merging**
